---

- hosts: all
  gather_facts: true
  tasks:
  - set_fact: es_major_version="6.x"
  - set_fact: es_version="6.2.4"

- hosts: master-nodes
  serial: 1
  gather_facts: true
  roles:
    - { role: es-admin }

- hosts: all:!master-nodes
  serial: 1
  gather_facts: true
  roles:
    - { role: es-admin }
